import { assets } from '../engine/assets';
import type { Renderer } from '../engine/renderer';
import UI from '../content/uiAtlas.json';

/** Metadata generated by tools/extract_ui.py. */
export const UI_ATLAS = UI as Record<
  string,
  {
    w: number;
    h: number;
    inset?: number[];
    hp?: number[];
    glyph?: number;
    chars?: string;
    content?: number[];
    /** [left, right) of the panel's drawn interior on its text rows. */
    textSpan?: number[];
  }
>;

export type FrameName = 'message' | 'panel' | 'fightMoves' | 'fightInfo';

/** Emerald's message box is teal, so its text is light with a dark shadow. */
export const INK = '#f8f8f8';
export const INK_SHADOW = '#4a5868';
export const INK_DARK = '#20202c';

/**
 * Draws one of the Emerald panels, stretched to any size. Returns false when
 * the art has not loaded, so callers can fall back to the plain frame.
 */
export function drawUiFrame(
  r: Renderer,
  name: FrameName,
  x: number,
  y: number,
  w: number,
  h: number,
): boolean {
  const image = assets.get(`ui:${name}`);
  const meta = UI_ATLAS[name];
  if (!image || !meta?.inset) return false;
  r.nineSlice(image, 0, 0, meta.w, meta.h, meta.inset, x, y, w, h);
  return true;
}

/** Plain frame used before the art loads, and by tests. */
export function drawPlainFrame(r: Renderer, x: number, y: number, w: number, h: number): void {
  r.rect(x, y, w, h, '#f8f4e4', true);
  r.strokeRect(x, y, w, h, '#3a3f66', true);
  r.strokeRect(x + 2, y + 2, w - 4, h - 4, '#a8b0d8', true);
}

/** True when the Emerald panels are available, so callers can pick text colours. */
export function uiArtLoaded(): boolean {
  return assets.get('ui:message') !== null;
}

/** Text with a one-pixel drop shadow, which is how Emerald renders on teal. */
export function drawShadowText(
  r: Renderer,
  text: string,
  x: number,
  y: number,
  color = INK,
  shadow = INK_SHADOW,
  size = 8,
): void {
  r.text(text, x + 1, y + 1, shadow, size, true);
  r.text(text, x, y, color, size, true);
}

/**
 * Emerald's own digit strip, used for HP readouts. Falls back to the built-in
 * font when the art is missing.
 */
export function drawNumber(r: Renderer, text: string, x: number, y: number): number {
  const image = assets.get('ui:numbers');
  const meta = UI_ATLAS.numbers;
  if (!image || !meta.glyph || !meta.chars) {
    r.text(text, x, y, INK_DARK, 8, true);
    return r.measure(text);
  }
  const glyph = meta.glyph;
  let cursor = x;
  for (const ch of text) {
    const index = meta.chars.indexOf(ch);
    if (index >= 0) {
      r.sprite(image, index * glyph, 0, glyph, meta.h, cursor, y, true);
    }
    cursor += glyph;
  }
  return cursor - x;
}

export function numberWidth(text: string): number {
  const meta = UI_ATLAS.numbers;
  return meta.glyph ? text.length * meta.glyph : text.length * 5;
}
