import { TILE } from '../engine/config';
import ATLAS from '../content/tileAtlas.json';

export type TileChar = string;

/** Atlas slot names, generated by tools/extract_tiles.py. */
export type AtlasName = keyof typeof ATLAS;

export const ATLAS_INDEX = ATLAS as Record<string, readonly number[]>;

/** Atlas cell for a slot name, or null when the name is unknown. */
export function atlasCell(name: string): { col: number; row: number } | null {
  const cell = ATLAS_INDEX[name];
  return cell ? { col: cell[0], row: cell[1] } : null;
}

export interface TileDef {
  solid: boolean;
  /** Atlas slot, or 'quad' to pick one of floorA..D by tile parity. */
  atlas: AtlasName | 'quad';
  /** Placeholder fill used when the atlas image has not loaded. */
  color: string;
  /** Darker cap drawn on the top of placeholder walls, to read as height. */
  capColor?: string;
  /**
   * Corner cuts are drawn as a diagonal, so the walkable half should not be
   * treated as floor: the whole tile blocks, but it *looks* like a cut corner.
   */
  slant?: boolean;
}

/**
 * Map characters. Chosen so a room stays legible as text in the source.
 *
 *   #  wall          .  octagon floor   ,  flat floor    D  doorway (warps)
 *   {  corner NW     }  corner NE       [  corner SW     ]  corner SE
 *   P  pillar        C  console         S  shelf
 *   b  light panel   o  boulder socket
 *
 * Boulders and rotating gates are entities, not tiles: the map marks their
 * start squares with O and G, which are plain floor as far as the map knows.
 */
export const TILES: Record<TileChar, TileDef> = {
  '#': { solid: true, atlas: 'wall', color: '#3d3f63', capColor: '#4d5079' },
  '.': { solid: false, atlas: 'quad', color: '#d5d2c0' },
  ',': { solid: false, atlas: 'floorFlat', color: '#cac7b3' },
  D: { solid: false, atlas: 'door', color: '#d8b24a' },
  '{': { solid: true, atlas: 'slantNW', color: '#3d3f63', slant: true },
  '}': { solid: true, atlas: 'slantNE', color: '#3d3f63', slant: true },
  '[': { solid: true, atlas: 'slantSW', color: '#3d3f63', slant: true },
  ']': { solid: true, atlas: 'slantSE', color: '#3d3f63', slant: true },
  P: { solid: true, atlas: 'pillar', color: '#8a8fae' },
  C: { solid: true, atlas: 'console', color: '#5d6480' },
  S: { solid: true, atlas: 'shelf', color: '#6b4c2f' },
  b: { solid: false, atlas: 'buttonOff', color: '#4a7fc1' },
  o: { solid: false, atlas: 'socket', color: '#9a9ab5' },
  // Entity spawn markers; the floor underneath is ordinary.
  O: { solid: false, atlas: 'quad', color: '#d5d2c0' },
  G: { solid: false, atlas: 'quad', color: '#d5d2c0' },
  ' ': { solid: true, atlas: 'wall', color: '#15141f' },
};

export function tileDef(char: TileChar): TileDef {
  return TILES[char] ?? TILES['#'];
}

export class TileMap {
  readonly width: number;
  readonly height: number;

  constructor(private rows: string[]) {
    this.height = rows.length;
    this.width = rows[0]?.length ?? 0;
    const ragged = rows.findIndex((r) => r.length !== this.width);
    if (ragged !== -1) {
      throw new Error(`Map row ${ragged} is ${rows[ragged].length} wide, expected ${this.width}`);
    }
  }

  get pixelWidth(): number {
    return this.width * TILE;
  }

  get pixelHeight(): number {
    return this.height * TILE;
  }

  inBounds(x: number, y: number): boolean {
    return x >= 0 && y >= 0 && x < this.width && y < this.height;
  }

  at(x: number, y: number): TileChar {
    return this.inBounds(x, y) ? this.rows[y][x] : '#';
  }

  def(x: number, y: number): TileDef {
    return tileDef(this.at(x, y));
  }

  /** Static geometry only; entities and locked doors are layered on by the scene. */
  isSolid(x: number, y: number): boolean {
    return !this.inBounds(x, y) || this.def(x, y).solid;
  }

  findAll(char: TileChar): Array<{ x: number; y: number }> {
    const found: Array<{ x: number; y: number }> = [];
    for (let y = 0; y < this.height; y++) {
      for (let x = 0; x < this.width; x++) {
        if (this.rows[y][x] === char) found.push({ x, y });
      }
    }
    return found;
  }
}

/** Which of the four octagon-floor tiles belongs at a given map square. */
export function quadName(x: number, y: number): AtlasName {
  const names = ['floorA', 'floorB', 'floorC', 'floorD'] as const;
  return names[(y & 1) * 2 + (x & 1)];
}
